
FROM ubuntu:latest
RUN apt-get update && apt-get install -y\
	g++ \
    valgrind \
    build-essential \
    gdb
RUN apt-get install -y git
RUN apt-get install -y bsdmainutils
RUN apt-get install -y file
